CREATE TABLE IF NOT EXISTS stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app	VARCHAR(50)                             NOT NULL,
    uri	VARCHAR(50)                             NOT NULL,
    hits BIGINT                                 NOT NULL,
    hits_unique BIGINT                          NOT NULL,
    CONSTRAINT pk_stat PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS stat_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    app	VARCHAR(50)                             NOT NULL,
    uri	VARCHAR(50)                             NOT NULL,
    ip	VARCHAR(12)                             NOT NULL,
    time_stamp VARCHAR(20)                      NOT NULL,
    stat_id BIGINT                              NOT NULL,

    CONSTRAINT pk_stat_event PRIMARY KEY (id),
    CONSTRAINT fk_stat_event_stat FOREIGN KEY (stat_id) REFERENCES stat(id) ON DELETE CASCADE
);

