CREATE TABLE IF NOT EXISTS endpoint_hit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    app	VARCHAR(50)                             NOT NULL,
    uri	VARCHAR(50)                             NOT NULL,
    ip	VARCHAR(12)                             NOT NULL,
    time_stamp VARCHAR(20)                      NOT NULL,

    CONSTRAINT pk_endpoint_hit PRIMARY KEY (id)
);

-- CREATE TABLE IF NOT EXISTS view_stats (
--     view_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     app	VARCHAR(50)                                 NOT NULL,
--     uri	VARCHAR(50)                                 NOT NULL,
--     hits BIGINT                                     NOT NULL,
--
--     CONSTRAINT pk_view_stats PRIMARY KEY (view_id)
-- );

CREATE TABLE IF NOT EXISTS view_stats (
    view_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    endpoint_hit_id BIGINT                          NOT NULL,
    hits BIGINT                                     NOT NULL,

    CONSTRAINT pk_view_stats PRIMARY KEY (view_id),
    CONSTRAINT fk_endpoint_hit_view_stats FOREIGN KEY (endpoint_hit_id) REFERENCES endpoint_hit(id) ON DELETE CASCADE
    );