CREATE TABLE IF NOT EXISTS stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app	VARCHAR(50)                             NOT NULL,
    uri	VARCHAR(50)                             NOT NULL,
    ip	VARCHAR(15)                             NOT NULL,
    time_stamp TIMESTAMP                     NOT NULL,
    hits BIGINT                                 NOT NULL,
    hits_unique BIGINT                          NOT NULL,
    CONSTRAINT pk_stat PRIMARY KEY (id)
    );


